M48
; DRILL file {KiCad 7.0.11+1} date jue 02 may 2024 20:53:03
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-02T20:53:03+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1122
%
G90
G05
T1
X5.3971Y-2.3068
X5.8971Y-3.3168
X8.9404Y-2.3068
X9.4404Y-3.3168
M30
